apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sondre-react-test-application
spec:
  environments:
    - name: production
      build:
        from: master
  components:
    - name: frontend
      dockerfile: prod.Dockerfile
      src: ./
      ports:
       - name: http
         port: 1024
      publicPort: http