apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: sondre-test
spec:
  environments:
    - name: production
      build:
        from: radix-local-dev
  components:
    - name: frontend 
      src: "."
      ports:
       - name: http
         port: 3000
      publicPort: http